<?php $this->headTitle('Bookings List'); ?>

<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">the Bookings Test</span></h1>
    <p>
        Congratulations! You have successfully setup the test. 
    </p>
    <p>
        This test utilizes zend Expressive to provide CRUD and 'add' via ajax.
    </p>
</div>

<div class="row">
    <div class="col-md-3">

    </div>

    <div class="col-md-6">
        <h2>
            <a href="https://github.com/zendframework/zend-diactoros" target="_blank">
                <i class="fa fa-exchange"></i> Bookings
            </a>
        </h2>
		<button><a href="http://bookings.localhost/bookings/add">add booking</a></button>
		<?php 
			if(count($bookings) > 0){
				echo "<table id='bookings_table'>
						<tr><td>ID</td><td>Username</td><td>Reason</td><td>requested_date</td><td>Created</td><td>Actions</td></tr>"; 
				foreach($bookings as $booking){
					echo "<tr><td>".$booking->id."</td><td>".$booking->username."</td><td>".$booking->reason."</td><td>".$booking->requested_date."</td><td>".$booking->created."</td><td><a href='/bookings/edit/".$booking->id."'>Edit</a>&nbsp;<a href='/bookings/delete/".$booking->id."' onclick=\"return confirm('Are you sure you want to Remove?');\">Delete</a></td></tr>";
				}
				echo "</table>";
			}else{
				echo "<h2>There are no Bookings. Consider Creating one!</h2>";
			}
		
		?>
    </div>

    <div class="col-md-3">

    </div>
</div>

<div class="row">
    <div class="col-md-4">
    </div>

    <div class="col-md-4">
    
	</div>

    <div class="col-md-4">
    
    </div>
</div>
