<?php 
$this->headTitle('Edit Booking'); 
$raw = "";
foreach($bookings as $book)$raw=$book;
?>


<div class="row">
    <div class="col-md-3">

    </div>

    <div class="col-md-6">
        <h2>
            <a href="https://github.com/zendframework/zend-diactoros" target="_blank">
                <i class="fa fa-exchange"></i> Edit Booking
            </a>
        </h2>
		<style type="text/css">
			#formElements{
				margin:auto;
				width:25%;
			}
		</style>
		<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>
		<script>
			var postApp = angular.module('myApp', []);
			postApp.controller('myCtrl', function($scope, $http) {
				$scope.user = {};
				$scope.user.id = "<?=$raw->id?>";
				$scope.user.username = "<?=$raw->username?>";
				$scope.user.reason = "<?=$raw->reason?>";
				$scope.user.requested_date = "<?=$raw->requested_date?>";
				$scope.hideElement = true;
				$scope.formConfirmation = "Enter Appointment";
				$scope.submitForm = function() {
					$http({
					  method  : 'POST',
					  url     : '/api/ajax',
					  data    : $scope.user,
					  headers : { 'Content-Type': 'application/x-www-form-urlencoded' } 
					}).then(function onSuccess(result) {
						if (result.data == 1){
							$scope.formConfirmation = "Success"; // show success message 
							$scope.hideElement = false; //remove the form from the dom
						}else{
							$scope.formConfirmation = result.data; // show the error
						}
					});
				};
			});
		</script>

		<div id="formElements" ng-app="myApp"  ng-controller="myCtrl">
		
			<h1 ng-show="formConfirmation">{{formConfirmation}}</h1>
			
			<div id="formFields"  ng-if="hideElement">
				<form name="userForm" ng-submit="submitForm()">
					<input type="hidden" ng-model="user.id">
					<p>Username : <input type="text" ng-model="user.username" placeholder="username" required></p>
					<p>Reason : <select ng-model="user.reason">
						<option value="abc">abc</option>
						<option value="fun">fun</option>
					</select></p>
					<p>Date/Time : <input type="text"  placeholder="select" ng-model="user.requested_date" required></p>
					<p><button type="submit" class="btn btn-primary">Submit</button></p>
				</form>
			</div>
		</div>
    </div>

    <div class="col-md-3">

    </div>
</div>

<div class="row">
    <div class="col-md-4">
    </div>

    <div class="col-md-4">

	</div>

    <div class="col-md-4">
    
    </div>
</div>
